// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamKimThe0000466.DbContexts;

#nullable disable

namespace PhamKimThe0000466.Migrations
{
    [DbContext(typeof(MyDbContext0000466De1))]
    partial class MyDbContext0000466De1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhamKimThe0000466.Entities.DoanhNghiep0000466De1", b =>
                {
                    b.Property<int>("DoanhNghiepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoanhNghiepId"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDoanhNghiep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DoanhNghiepId");

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.ToTable("DoanhNghieps");
                });

            modelBuilder.Entity("PhamKimThe0000466.Entities.SanPham0000466De1", b =>
                {
                    b.Property<int>("SanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanPhamId"));

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SanPhamId");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("PhamKimThe0000466.Entities.SanPhamDoanhNghiep0000466De1", b =>
                {
                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("DoanhNghiepId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("SanPhamDoanhNghieps");
                });

            modelBuilder.Entity("PhamKimThe0000466.Entities.SanPhamDoanhNghiep0000466De1", b =>
                {
                    b.HasOne("PhamKimThe0000466.Entities.DoanhNghiep0000466De1", "DoanhNghiep")
                        .WithMany("SanPhamDoanhNghieps")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhamKimThe0000466.Entities.SanPham0000466De1", "SanPham")
                        .WithMany("SanPhamDoanhNghieps")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("PhamKimThe0000466.Entities.DoanhNghiep0000466De1", b =>
                {
                    b.Navigation("SanPhamDoanhNghieps");
                });

            modelBuilder.Entity("PhamKimThe0000466.Entities.SanPham0000466De1", b =>
                {
                    b.Navigation("SanPhamDoanhNghieps");
                });
#pragma warning restore 612, 618
        }
    }
}
